import json
import os
import time

import gymnasium as gym
import numpy as np
import torch

from utils import plot_training_curves, record_policy_video
from data_collection import collect_parallel_trajectories
from policy import build_policy
from gpomdp import compute_gpomdp_loss, apply_npg_preconditioning

# Comment key: M says what the function does. A says how it works and why.


#M: Loads training settings from a JSON file.
#A: Opens the file and returns its contents as a Python dictionary.
def load_config(path="config.json"):
    with open(path, "r") as f:
        return json.load(f)


#M: Saves reward curves together with the seed that produced each curve.
#A: Converts values to fixed NumPy types and stores rewards and seeds in one NPZ file.
def save_training_rewards(output_dir, rewards, seeds, filename="training_rewards.npz"):
    """Save per-seed training curves to an .npz archive.

    rewards: array-like [n_seeds, n_iterations].
    seeds:   sequence of length n_seeds; seeds[i] is the unique id for rewards[i],
             so individual seed performance can be recovered downstream.
    """
    rewards = np.asarray(rewards, dtype=np.float32)
    seeds = np.asarray(seeds, dtype=np.int64)
    assert rewards.shape[0] == seeds.shape[0], "one seed id required per reward curve"

    path = os.path.join(output_dir, filename)
    np.savez(path, rewards=rewards, seeds=seeds)
    return path


#M: Chooses the device used for policy and gradient calculations.
#A: Auto mode tries CUDA, then Apple MPS, and finally CPU.
def resolve_device(name=None) -> torch.device:
    """Resolve a device string to a torch.device.

    'auto' (or None) prefers CUDA, then Apple MPS, then CPU.
    """
    if name in (None, "auto"):
        if torch.cuda.is_available():
            return torch.device("cuda")
        if torch.backends.mps.is_available():
            return torch.device("mps")
        return torch.device("cpu")
    return torch.device(name)


#M: Prepares a function that can create one training environment.
#A: AsyncVectorEnv needs a factory so every worker can create its own environment.
def make_env(env_id: str, seed: int | None, horizon: int | None = None):
    # AsyncVectorEnv requires a factory (thunk) rather than an env instance
    # so each worker can construct its own isolated copy.
    #M: Creates, limits, and seeds one environment inside a worker.
    #A: Builds the environment only when AsyncVectorEnv starts that worker.
    def thunk():
        env = gym.make(env_id)

        if horizon is not None and horizon > 0:
            env = gym.wrappers.TimeLimit(
                env,
                max_episode_steps=horizon,
            )

        if seed is not None:
            env.reset(seed=seed)

        return env

    return thunk


#M: Trains one policy using one random seed.
#A: Repeatedly collects trajectories, computes the loss, updates the policy,
#   records rewards, and saves the requested outputs.
def run_single_training(cfg: dict):
    output_dir = cfg.get("output_dir", "runs")
    os.makedirs(output_dir, exist_ok=True)

    torch.manual_seed(cfg["seed"])
    np.random.seed(cfg["seed"])

    device = resolve_device(cfg.get("device", "auto"))
    print(f"Device       : {device}")

    env = gym.make(cfg["env_id"])

    policy = build_policy(cfg, env)
    policy.to(device)

    if cfg.get("use_npg", False):
        optimizer = torch.optim.SGD(policy.parameters(), lr=cfg["lr"])
    else:
        optimizer = torch.optim.Adam(policy.parameters(), lr=cfg["lr"])

    env_fns = [
        make_env(
            env_id=cfg["env_id"],
            seed=cfg["seed"] + i,
            horizon=cfg.get("horizon", None),
        )
        for i in range(cfg["n_envs"])
    ]

    # Rollout collection is the dominant wall-clock cost; N workers run concurrently to amortise it.
    train_envs = gym.vector.AsyncVectorEnv(env_fns)

    training_rewards = []
    best_reward = float("-inf")
    best_state_dict = None

    training_start = time.perf_counter()

    try:
        for iteration in range(cfg["n_iterations"]):
            t0 = time.perf_counter()

            trajectories = collect_parallel_trajectories(
                envs=train_envs,
                policy=policy,
                n_trajectories_per_env=cfg["n_trajectories"],
                clip_actions=cfg.get("clip_actions", True),
                device=device,
            )

            t1 = time.perf_counter()

            batch_reward = float(np.mean([
                sum(traj.rewards) for traj in trajectories
            ]))

            # `batch_reward` was generated by the current (pre-update) policy.
            # Preserve those exact weights when this is the best observed batch.
            if batch_reward > best_reward:
                best_reward = batch_reward
                best_state_dict = {
                    key: value.detach().cpu().clone()
                    for key, value in policy.state_dict().items()
                }

            debug = iteration == 0

            optimizer.zero_grad()

            loss = compute_gpomdp_loss(
                policy=policy,
                trajectories=trajectories,
                gamma=cfg["gamma"],
                center_returns=cfg["center_returns"],
                normalize_returns=cfg["normalize_returns"],
                entropy_coeff=cfg.get("entropy_coeff", 0.0),
                returns_implementation=cfg.get("returns_implementation", "recursive"),
                device=device,
                debug=debug,
            )

            loss.backward()

            if cfg.get("use_npg", False):
                # Note: re-derives states/actions/mask from `trajectories` internally
                # (trajectories_to_tensors runs again here) rather than reusing the ones
                # already built inside compute_gpomdp_loss above -- redundant but not incorrect.
                apply_npg_preconditioning(
                    policy=policy,
                    trajectories=trajectories,
                    damping=cfg.get("npg_damping", 1e-2),
                    device=device,
                    debug=debug,
                )

            optimizer.step()

            t2 = time.perf_counter()

            rollout_time = t1 - t0
            update_time = t2 - t1
            iteration_time = t2 - t0

            n_steps = sum(len(traj.rewards) for traj in trajectories)
            samples_per_sec = n_steps / iteration_time

            training_rewards.append(batch_reward)

            print(
                f"Iteration {iteration:04d} | "
                f"train reward: {batch_reward:.2f} | "
                f"best: {best_reward:.2f} | "
                f"rollout: {rollout_time:.3f}s | "
                f"update: {update_time:.3f}s | "
                f"total: {iteration_time:.3f}s | "
                f"samples/s: {samples_per_sec:.0f}"
            )

    finally:
        train_envs.close()
        env.close()

    training_time = time.perf_counter() - training_start
    print(f"training time {training_time:.2f}s")

    save_training_rewards(
        output_dir,
        np.array([training_rewards], dtype=np.float32),
        [cfg["seed"]],
    )

    if cfg.get("save_plots", True):
        plot_training_curves(
            training_rewards=training_rewards,
            save_dir=output_dir,
        )

    if cfg.get("save_checkpoints", True):
        checkpoint_dir = os.path.join(output_dir, "checkpoints")
        os.makedirs(checkpoint_dir, exist_ok=True)
        scored = cfg.get("scored_checkpoints", False)
        if best_state_dict is not None:
            best_name = f"best_{best_reward:.1f}.pt" if scored else "best.pt"
            torch.save(best_state_dict, os.path.join(checkpoint_dir, best_name))
        final_score = training_rewards[-1] if training_rewards else 0.0
        final_name = f"final_{final_score:.1f}.pt" if scored else "final.pt"
        torch.save(policy.state_dict(), os.path.join(checkpoint_dir, final_name))

    if cfg.get("record_video", False):
        # Video recording feeds CPU state tensors to the policy, so run it on CPU.
        policy.to("cpu")
        # Restore the best weights found during training before recording.
        if best_state_dict is not None:
            policy.load_state_dict(best_state_dict)
        record_policy_video(
            env_id=cfg["env_id"],
            policy=policy,
            video_dir=os.path.join(output_dir, "videos"),
            seed=cfg["seed"] + 20_000,
        )

    return policy, training_rewards


#M: Records a video using the strongest seed from a multi-seed run.
#A: Chooses the best final-window reward, loads that seed's checkpoint, and replays it.
def _record_best_seed_video(cfg, output_dir, all_training_rewards, seeds, final_window=100):
    """Record a video from the best-performing seed's checkpoint.

    "Best" = highest mean return over the last `final_window` iterations. The seed's
    weights are loaded from output_dir/seed<seed>/checkpoints/best.pt (written during
    the multiseed loop) and replayed into output_dir/videos/.
    """
    rewards = np.asarray(all_training_rewards, dtype=np.float64)
    window = min(final_window, rewards.shape[1])
    scores = rewards[:, -window:].mean(axis=1)
    best_idx = int(np.argmax(scores))
    best_seed = seeds[best_idx]
    print(f"\nBest seed: {best_seed} (final-{window} mean {scores[best_idx]:.1f}) — recording video")

    checkpoint_path = os.path.join(output_dir, f"seed{best_seed}", "checkpoints", "best.pt")
    if not os.path.exists(checkpoint_path):
        print(f"Warning: no checkpoint at {checkpoint_path}; skipping video")
        return

    # Replay runs on CPU (record_policy_video builds CPU state tensors).
    env = gym.make(cfg["env_id"])
    policy = build_policy(cfg, env)
    env.close()

    state_dict = torch.load(checkpoint_path, map_location="cpu")
    policy.load_state_dict(state_dict)
    policy.eval()

    record_policy_video(
        env_id=cfg["env_id"],
        policy=policy,
        video_dir=os.path.join(output_dir, "videos"),
        seed=int(best_seed) + 20_000,
    )


#M: Repeats training for several seeds and keeps every reward curve.
#A: Calls single-seed training once per seed, saves separate and combined results,
#   and optionally records the best seed.
def run_multiseed(cfg: dict):
    seeds = cfg.get("seeds", [cfg["seed"]])
    output_dir = cfg.get("output_dir", "runs")
    os.makedirs(output_dir, exist_ok=True)

    want_video = cfg.get("record_video", False)

    all_training_rewards = []

    for seed in seeds:
        print(f"\n========== Running seed {seed} ==========")

        seed_cfg = dict(cfg)
        seed_cfg["seed"] = seed
        seed_cfg["record_video"] = False   # never record during per-seed training
        seed_cfg["save_plots"] = False     # CI plot is produced downstream in the notebook

        if want_video:
            # Keep each seed's checkpoint in its own subdir so the best seed can be
            # replayed after all seeds finish, without seeds clobbering each other.
            seed_cfg["save_checkpoints"] = True
            seed_cfg["scored_checkpoints"] = False  # deterministic best.pt filename
            seed_cfg["output_dir"] = os.path.join(output_dir, f"seed{seed}")
            os.makedirs(seed_cfg["output_dir"], exist_ok=True)
        else:
            seed_cfg["save_checkpoints"] = False  # per-seed checkpoints would overwrite

        _, seed_rewards = run_single_training(seed_cfg)

        all_training_rewards.append(seed_rewards)

        # One uniquely-named file per seed so each seed's curve is identifiable on disk.
        per_seed_path = save_training_rewards(
            output_dir,
            np.array([seed_rewards], dtype=np.float32),
            [seed],
            filename=f"training_rewards_seed{seed}.npz",
        )
        print(f"Saved per-seed rewards: {per_seed_path}")

    # Also save the combined matrix (all seeds, labeled) for the comparison notebook.
    all_training_rewards = np.asarray(all_training_rewards, dtype=np.float32)

    save_training_rewards(output_dir, all_training_rewards, seeds)

    if want_video:
        _record_best_seed_video(cfg, output_dir, all_training_rewards, seeds)


#M: Starts single-seed or multi-seed training from a saved configuration.
#A: Reads run_mode from the JSON config and calls the matching training function.
def train_from_config(config_path="config.json"):
    cfg = load_config(config_path)
    run_mode = cfg.get("run_mode", "single")

    if run_mode == "single":
        return run_single_training(cfg)

    if run_mode == "multiseed":
        return run_multiseed(cfg)

    raise ValueError(f"Unknown run_mode: {run_mode}")


if __name__ == "__main__":
    train_from_config()
